# Generated by Django 4.1.5 on 2023-02-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Производитель')),
                ('comments', models.CharField(blank=True, max_length=100, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='NameСartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название картриджа')),
                ('comments', models.CharField(blank=True, max_length=100, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Название картриджа',
                'verbose_name_plural': 'Названия картриджей',
            },
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(db_index=True, unique=True, verbose_name='Штрихкод')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Помещение')),
                ('branch', models.CharField(blank=True, max_length=50, verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='Cartridges',
            fields=[
                ('barcode', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Штрихкод')),
                ('date', models.DateTimeField(verbose_name='Дата изменения')),
                ('cartName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cartridge.nameсartridge')),
                ('manufacturerName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cartridge.manufacturer')),
                ('placeName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartridge.placements')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
    ]
