# Generated by Django 4.1.5 on 2023-02-09 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0002_alter_cartridges_placename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 9, 17, 3, 748283), verbose_name='Дата изменения'),
        ),
    ]
