# Generated by Django 4.1.5 on 2023-02-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0003_alter_cartridges_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='09.02.2023 11:17', verbose_name='Дата изменения'),
        ),
    ]
