# Generated by Django 4.1.5 on 2023-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0004_alter_cartridges_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='09.02.2023 13:37', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='nameсartridge',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='placements',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Корпус'),
        ),
    ]
