# Generated by Django 4.1.5 on 2023-02-13 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0005_alter_cartridges_date_alter_manufacturer_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='barcode',
            field=models.IntegerField(db_index=True, max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='13.02.2023 08:13', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='placeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartridge.placements'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='comments',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='nameсartridge',
            name='comments',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='placements',
            name='barcode',
            field=models.IntegerField(db_index=True, max_length=13, unique=True, verbose_name='Штрихкод'),
        ),
    ]
