# Generated by Django 4.1.5 on 2023-02-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0006_alter_cartridges_barcode_alter_cartridges_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='barcode',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='13.02.2023 08:29', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='placements',
            name='barcode',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Штрихкод'),
        ),
    ]
