# Generated by Django 4.1.5 on 2023-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0007_alter_cartridges_barcode_alter_cartridges_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridges',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='barcode',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='14.02.2023 11:02', verbose_name='Дата изменения'),
        ),
    ]
