# Generated by Django 4.1.5 on 2023-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0008_cartridges_id_alter_cartridges_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='14.02.2023 11:04', verbose_name='Дата изменения'),
        ),
    ]
