# Generated by Django 4.1.5 on 2023-02-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0009_alter_cartridges_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridges',
            name='choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placements',
            name='choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='22.02.2023 11:18', verbose_name='Дата изменения'),
        ),
    ]
