# Generated by Django 4.1.5 on 2023-02-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0010_cartridges_choice_placements_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='Выбрать'),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='22.02.2023 11:20', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='placements',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='Выбрать'),
        ),
    ]
