# Generated by Django 4.1.5 on 2023-04-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0011_alter_cartridges_choice_alter_cartridges_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridges',
            name='col',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Перезаправки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='07.04.2023 08:51', verbose_name='Дата изменения'),
        ),
    ]
