# Generated by Django 4.1.5 on 2023-04-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0012_cartridges_col_alter_cartridges_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Таблица')),
                ('record_id', models.IntegerField(null=True, verbose_name='ID записи')),
                ('action_on_model', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=50, null=True, verbose_name='Действие')),
                ('data', models.JSONField(default=dict, verbose_name='Изменяемые данные модели')),
            ],
            options={
                'verbose_name': 'Журнал изменений',
                'verbose_name_plural': 'Журналы изменений',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='14.04.2023 11:11', verbose_name='Дата изменения'),
        ),
    ]
