# Generated by Django 4.1.5 on 2023-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0013_changelog_status_alter_cartridges_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridges',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='placements',
            name='choice',
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='14.04.2023 11:56', verbose_name='Дата изменения'),
        ),
    ]
