# Generated by Django 4.1.5 on 2023-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0022_remove_changelog_action_on_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='11.05.2023 11:32', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='cartName_h',
            field=models.CharField(default=None, max_length=50, verbose_name='Модель'),
        ),

        migrations.AlterField(
            model_name='changelog',
            name='manufacturerName_h',
            field=models.CharField(default=None, max_length=50, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='status_h',
            field=models.CharField(max_length=50, unique=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalcartridges',
            name='date',
            field=models.DateTimeField(default='11.05.2023 11:32', verbose_name='Дата изменения'),
        ),
    ]
