# Generated by Django 4.1.5 on 2023-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0023_alter_cartridges_date_alter_changelog_cartname_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='date',
            field=models.DateTimeField(default='11.05.2023 11:33', verbose_name='Дата изменения'),
        ),


        migrations.AlterField(
            model_name='historicalcartridges',
            name='date',
            field=models.DateTimeField(default='11.05.2023 11:33', verbose_name='Дата изменения'),
        ),
    ]
